apiVersion: v1
kind: Service
metadata:
  name: mt-rest-api-app-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.type }}
  selector:
    app: mt-rest-api-app
