apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-rest-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-rest-api-app
  template:
    metadata:
      labels:
        app: mt-rest-api-app
    spec:
      containers:
      - name: mt-rest-api-app
        image: 386613981817.dkr.ecr.eu-west-2.amazonaws.com/xds-gitops-repo:fe852ca45975b357e107aecf0149ea79dd1c2c1e
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
