replicaCount: 1
image:
  repository: 386613981817.dkr.ecr.eu-west-2.amazonaws.com/xds-gitops-repo
  pullPolicy: IfNotPresent
  tag: "b9dda8cf8214cfc5f186e40166aa8ddbfe6af484"

service:
  type: NodePort
  port: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
